export const UI_CONSTANTS = {
  GRID: {
    CELL_SIZE: 40,
    GAP: 4,
    PADDING: 8,
    BORDER_RADIUS: 4,
  },
  TYPOGRAPHY: {
    FONT_SIZE_INPUT: 16,
    FONT_SIZE_BODY: 14,
    FONT_SIZE_SMALL: 12,
    FONT_SIZE_DISPLAY: 18,
  },
  ANIMATION: {
    FADE_OUT_DURATION: "0.5s",
    TRANSITION_DURATION: "0.3s",
    BLINK_DURATION: "1s",
  },
} as const;
